//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeListReport
    {
        public string CNIC { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public decimal Salary { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
    }
}
