//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan_Application()
        {
            this.Loan_Info = new HashSet<Loan_Info>();
        }
    
        public int App_ID { get; set; }
        public string Reason_Loan { get; set; }
        public decimal Loan_Amount { get; set; }
        public System.DateTime Pay_Back_time { get; set; }
        public int Loan_ID { get; set; }
        public string CNIC { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Loan_Policy Loan_Policy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loan_Info> Loan_Info { get; set; }
    }
}
