//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_Info
    {
        public int App_ID { get; set; }
        public int Pay_ID { get; set; }
        public string Status { get; set; }
        public string Reason_Of_Rejection { get; set; }
        public int Approval_ID { get; set; }
    
        public virtual Loan_Application Loan_Application { get; set; }
        public virtual Loan_Approval Loan_Approval { get; set; }
    }
}
