//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApprovalReport
    {
        public int Approval_ID { get; set; }
        public int No_of_Installments { get; set; }
        public decimal Installments_Amount { get; set; }
        public string Discription { get; set; }
        public System.DateTime Approved_date { get; set; }
    }
}
