//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_Policy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan_Policy()
        {
            this.Loan_Application = new HashSet<Loan_Application>();
        }
    
        public int Loan_ID { get; set; }
        public string Loan_type { get; set; }
        public string Loan_Discription { get; set; }
        public decimal Amount { get; set; }
        public int Max_Installments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loan_Application> Loan_Application { get; set; }
    }
}
