//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanPolicyReport
    {
        public int Loan_ID { get; set; }
        public string Loan_type { get; set; }
        public string Loan_Discription { get; set; }
        public decimal Amount { get; set; }
        public int Max_Installments { get; set; }
    }
}
